version: '2'
services:
  hospitalsystem-app:
    image: hospitalsystem
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://hospitalsystem-mysql:3306/hospitalsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://hospitalsystem-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://hospitalsystem-elasticsearch:9200
    ports:
      - 8080:8080
  hospitalsystem-mysql:
    extends:
      file: mysql.yml
      service: hospitalsystem-mysql
  hospitalsystem-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: hospitalsystem-elasticsearch
